gcc-4.8.5 - backport of PR/82886
 -finit-derived (see also PR/33430)

 +PR/57093 Seg. fault - coarrays 
 +PR/87352 which depends on PR/81447
 +libiconv-1.16, if you've faced ie: 
  dyld: Symbol not found: _iconv
 
  To upgrade "libiconv", run:
 ./port install libiconv0 
 ./port   clean gettext 
 ./port --force install   gettext
 ./port install libiconv